---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli-ruby
    tag: 'latest'

inputs:
- name: uaa-war
- name: source

run:
  path: source/uaa/ci/tasks/test.sh

params:
  CF_API_URL:
  CF_USER_NAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SKIP_SSL:
  CF_SPACE:
  CF_APP_DOMAIN: 
